--vim.keymap.set("n", "<leader>fg", ":GitFiles<CR>")
vim.keymap.set("n", "<leader>fr", ":Rg<CR>")
--vim.keymap.set("n", "<leader>ff", ":Files<CR>")
vim.keymap.set("n", "<leader>fc", ":Commands<CR>")
vim.keymap.set("n", "<leader>fm", ":Maps<CR>")
vim.keymap.set("n", "<leader>fb", ":Buffers<CR>")
vim.keymap.set("n", "<leader>fs", ":Snippets<CR>")
